const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  content: [
    './public/*.html',
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js',
    './app/views/**/*.{erb,haml,html,slim}'
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter var', ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/container-queries'),
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        ideabug: {
          primary: '#0f766e',
          'primary-content': '#ffffff',
          secondary: '#475569',
          'secondary-content': '#ffffff',
          accent: '#b45309',
          'accent-content': '#ffffff',
          neutral: '#202624',
          'neutral-content': '#f8faf9',
          'base-100': '#fcfcfb',
          'base-200': '#f4f5f3',
          'base-300': '#e2e5e2',
          'base-content': '#202624',
          info: '#2563eb',
          success: '#15803d',
          warning: '#b45309',
          error: '#b91c1c',
          '--rounded-box': '0.625rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '9999px',
          '--animation-btn': '0.15s',
          '--animation-input': '0.15s',
          '--btn-focus-scale': '1',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.5rem',
        },
      },
      {
        ideabug_dark: {
          primary: '#5eead4',
          'primary-content': '#082f2b',
          secondary: '#a7b0ac',
          'secondary-content': '#171b19',
          accent: '#fbbf24',
          'accent-content': '#422006',
          neutral: '#0d100f',
          'neutral-content': '#e8ebe9',
          'base-100': '#151917',
          'base-200': '#1c211f',
          'base-300': '#303733',
          'base-content': '#e8ebe9',
          info: '#60a5fa',
          success: '#4ade80',
          warning: '#fbbf24',
          error: '#f87171',
          '--rounded-box': '0.625rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '9999px',
          '--animation-btn': '0.15s',
          '--animation-input': '0.15s',
          '--btn-focus-scale': '1',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.5rem',
        },
      },
    ],
  },
}
